# Site settings
title: Charlie Lee
author: Charlie Lee
description: >
  Charlie Lee is a software developer and the creator of Boats Animator (no I didn't invent Litecoin).
footer_text: "&copy; 2020 Charlie Lee"
navigation:
- text: Home
  url: /
- text: Boats Animator
  url: /boats-animator
- text: Contact
  url: contact
permalink: /:year/:month/:title/

# Collections
collections:
  category_pages:
    output: true
    permalink: /category/:path/
  feeds:
    output: true
    permalink: /feed/:path
  projects:
    output: true
    permalink: /project/:path/
  projects-archive:
    output: true
    permalink: /archive/:path/

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-redirect-from
